//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace designBIB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("designBIB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel File (*.xlsx)|*.xlsx.
        /// </summary>
        internal static string DialogFileFormat {
            get {
                return ResourceManager.GetString("DialogFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string Form1_Form1_Load__space {
            get {
                return ResourceManager.GetString("Form1_Form1_Load__space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ärendet är upplagdt.
        /// </summary>
        internal static string Form1_metroButton1_Click_Ärendet_är_upplagdt {
            get {
                return ResourceManager.GetString("Form1_metroButton1_Click_Ärendet_är_upplagdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update was executed .
        /// </summary>
        internal static string Form1_UpdateCheck_update_was_executed_ {
            get {
                return ResourceManager.GetString("Form1_UpdateCheck_update_was_executed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel File (*.xlsx)|*.xlsx.
        /// </summary>
        internal static string FrmElever_btnCheckKlasser_Click_Excel_File____xlsx____xlsx {
            get {
                return ResourceManager.GetString("FrmElever_btnCheckKlasser_Click_Excel_File____xlsx____xlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stämmer inte överens med något användar ID, kolla stavningen eller lägg till användare.
        /// </summary>
        internal static string FrmProdukter_dataGridView1_CellValidating_Stämmer_inte_överens_med_något_användar_ID__kolla_stavningen_eller_lägg_till_användare {
            get {
                return ResourceManager.GetString("FrmProdukter_dataGridView1_CellValidating_Stämmer_inte_överens_med_något_användar" +
                        "_ID__kolla_stavningen_eller_lägg_till_användare", resourceCulture);
            }
        }
    }
}
